/** Define ids for each page. */
export const PAGE_IDS = {
  ABOUT_US: 'about-us',
  ADD_STUFF: 'add-stuff',
  EDIT_STUFF: 'edit-stuff',
  LANDING: 'landing',
  ADD_FINANCIAL_PROFILE: 'add-financial-profile',
  LIST_STUFF: 'list-stuff',
  LIST_STUFF_ADMIN: 'list-stuff-admin',
  MANAGE_DATABASE: 'manage-database',
  NOT_AUTHORIZED: 'not-authorized',
  NOT_FOUND: 'not-found',
  SIGN_IN: 'sign-in',
  SIGN_OUT: 'sign-out',
  SIGN_UP: 'sign-up',
  BALANCE_SHEET_INPUT: 'balance-sheet-input',
  BUDGET_FORM: 'budget-form',
  FINANCIAL_PROFILES: 'financial-profiles',
  DASHBOARD: 'dashboard',
  CONTACT_US: 'contact-us',
  USER_GUIDE: 'user-guide',
  UPLOAD_FILE: 'upload-file',
  FAQ: 'faq',
  AUDITED_FS: 'audited-fs',
};
